Ensure we use Bedtools 2.23

diff --git a/sequence_handling b/sequence_handling
--- a/sequence_handling
+++ b/sequence_handling
@@ -164,6 +164,8 @@ case "${ROUTINE}" in
         source "${SEQUENCE_HANDLING}"/Handlers/Coverage_Mapping.sh
         checkDependencies Coverage_Mapping_Dependencies[@] # Check to see if the dependencies are installed
         if [[ "$?" -ne 0 ]]; then exit 1; fi # If we're missing a dependency, exit out with error
+        checkVersion bedtools 2.23 # Check to see that we have bedtools version 2.23
+        if [[ "$?" -ne 0 ]]; then echo "Please use Bedtools version 2.23" >&2; exit 1; fi # If not, exit out with error
         checkSamples "${BAM_SAMPLES}" # Check to see if samples and sample list exists
         if [[ "$?" -ne 0 ]]; then exit 1; fi # If we're missing a sample or our list, exit out with error
         if ! [[ -f "${REF_ANN}" ]]; then echo "Failed to find reference annotation file, exiting..." >&2; exit 1; fi # Check to see if the reference annotation file exists. If not, exit
