GenomicsDBImport can now parallelize across regions; GenotypeGVCFs still in progress

diff --git a/sequence_handling b/sequence_handling
--- a/sequence_handling
+++ b/sequence_handling
@@ -362,26 +362,64 @@ case "${ROUTINE}" in
 	        checkDict "${REF_GEN}" # Check to make sure our reference genome has a dict file
             if [[ "$?" -ne 0 ]]; then echo "Generating dictionary file for ${REF_GEN}..." >&2; createDict "${REF_GEN}" "${HC_MEM}" "${PICARD_JAR}"; fi # If not, generate one
 	        #if [[ -n ${REGIONS_FILE} ]]; then
-            if [[ -n ${CUSTOM_INTERVALS} ]]; then
+            # If we have custom intervals set, check if we are parallelizing across regions
+            if [[ -n "${CUSTOM_INTERVALS}" ]]; then
 		        analysisType="targeted"
-		        #intvlFile="${REGIONS_FILE}"
                 intvlFile="${CUSTOM_INTERVALS}"
+                # If we are parallelizing across regions, we will have one gendb
+                # workspace for every custom interval
+                if [ "${PARALLELIZE}" == "true" ]; then
+                    # For GATK-style .list or .intervals file in the form <chr>:<start>-<stop>
+                    # GATK 4 will throw an error if the first position starts at 0.
+                    # Check for this. Fix is to change 0 start position to 1 start position.
+                    temp_start_pos=$(head -n 1 "${CUSTOM_INTERVALS}" | cut -d':' -f 2 | cut -d'-' -f 1)
+                    if [[ "${temp_start_pos}" -eq 0 ]]; then
+                        echo "GATK-style .list or .intervals file uses 1-based coordinates. Please check your custom intervals file to make sure there are no positions that start at 0. If so, change so the starting position is 1. See docs: https://software.broadinstitute.org/gatk/documentation/article?id=11009. Exiting..." >&2
+                        exit 31
+                    fi
+                    # Use CUSTOM_INTERVALS to determine array limit
+                    NUM_INTVLS=$(wc -l "${CUSTOM_INTERVALS}" | cut -d ' ' -f 1)
+                    SINGLE_ARRAY_LIMIT=$[${NUM_INTVLS} - 1]
+                else
+                    # We are NOT parallelizing across regions
+                    # List of custom intervals is given to GATK, but only a single
+                    # gendb workspace is created.
+                    SINGLE_ARRAY_LIMIT="0"
+                fi
 	        else
 		        analysisType="WGS"
 		        intvlFile="NA"
+                # Use the number of chromosomes to set array limit
+                SINGLE_ARRAY_LIMIT=$[${NUM_CHR} - 1] # Get the maximum number of Torque tasks (# in array - 1)
 	        fi
             # With gatk4, individual vcf files have to be combined into a DB
             # GenomicsDBImport takes a long time, so omit it if it is already combined.
-            if [ -d "${OUT_DIR}"/Genotype_GVCFs/combinedDB ] && [ $(ls "${OUT_DIR}/Genotype_GVCFs/combinedDB" | wc -l) -gt 0 ]; then
+            # Only check if we are NOT parallelizing across regions (creating a single workspace)
+            if [ -d "${OUT_DIR}"/Genotype_GVCFs/combinedDB ] && [ $(ls "${OUT_DIR}/Genotype_GVCFs/combinedDB" | wc -l) -gt 0 ] && [ "${SINGLE_ARRAY_LIMIT}" -eq 0 ]; then
                 echo "INFO: *** Using pre-existing ${OUT_DIR}/Genotype_GVCFs/combinedDB ***" >> "${ERROR}/Genomics_DB_Import.log"
                 echo "There is a pre-existing ${OUT_DIR}/Genotype_GVCFs/combinedDB. If this is not what you want to use, delete/rename the existing combinedDB directory and re-run Genomics_DB_Import. If this is correct, proceed to Genotype_GVCFs. Exiting..."
             else
+                echo "Max array index is ${SINGLE_ARRAY_LIMIT}...">&2
                 if [[ "${USE_PBS}" == true ]]; then
-                    echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Genomics_DB_Import.sh && GenomicsDBImport ${GVCF_LIST} ${OUT_DIR}/Genotype_GVCFs/combinedDB ${REF_GEN} ${analysisType} ${intvlFile} ${TMP} ${GDBI_MEM}" | qsub -t 0 -l "${GDBI_QSUB}" -q "${GDBI_QUEUE}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}"_DBImport
+                    # If we have enough samples for a task array
+                    if [[ "${SINGLE_ARRAY_LIMIT}" -ne 0 ]]; then
+                        # If CUSTOM_JOB_ARR is NOT set (only gets set if user uses -t flag)
+                        if [[ -z ${CUSTOM_JOB_ARR+x} ]]
+                        then
+                            echo "Using default array limit from 0 to ${SINGLE_ARRAY_LIMIT}"
+                            echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Genomics_DB_Import.sh && GenomicsDBImport ${GVCF_LIST} ${OUT_DIR} ${REF_GEN} ${analysisType} ${intvlFile} ${TMP} ${GDBI_MEM}" "${PARALLELIZE}" | qsub -t 0-"${SINGLE_ARRAY_LIMIT}" -l "${GDBI_QSUB}" -q "${GDBI_QUEUE}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}"_DBImport
+                        else
+                            # Use job arrays following -t flag
+                            echo "Using custom job arrays following -t flag: ${CUSTOM_JOB_ARR}" >&2
+                            echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Genomics_DB_Import.sh && GenomicsDBImport ${GVCF_LIST} ${OUT_DIR} ${REF_GEN} ${analysisType} ${intvlFile} ${TMP} ${GDBI_MEM}" "${PARALLELIZE}" | qsub -t 0-"${CUSTOM_JOB_ARR}" -l "${GDBI_QSUB}" -q "${GDBI_QUEUE}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}"_DBImport
+                        fi
+                    else # If we are creating a single gendb workspace
+                        echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Genomics_DB_Import.sh && GenomicsDBImport ${GVCF_LIST} ${OUT_DIR} ${REF_GEN} ${analysisType} ${intvlFile} ${TMP} ${GDBI_MEM}" "${PARALLELIZE}" | qsub -t 0 -l "${GDBI_QSUB}" -q "${GDBI_QUEUE}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}"_DBImport
+                    fi
                 else
                     (source "${CONFIG}" && source "${SEQUENCE_HANDLING}/Handlers/Genotype_GVCFs.sh" && GenomicsDBImport "${GVCF_LIST}" "${OUT_DIR}/Genotype_GVCFs/combinedDB" "${REF_GEN}" ${analysisType} "${intvlFile}" "${TMP}") >> "${ERROR}/Genotype_GVCFs.log" 2>&1
                 fi
-                echo "Making database. Please run Genotype_GVCFs after the database is complete. Exiting..."
+                echo "Making database. Please run Genotype_GVCFs after the database is complete."
                 exit 1
             fi
 	    elif checkVersion gatk 3.8.0 ; then
@@ -428,7 +466,7 @@ case "${ROUTINE}" in
             # As of Sep 23, 2019 it seems like we need to be in Genotype_GVCFs for GATK4 to find database
             # CL is unable to get it working with a relative or absolute filepath to the database
             #input_gvcf="gendb://${OUT_DIR}/Genotype_GVCFs/combinedDB"
-            input_gvcf="gendb://combinedDB"
+            input_gvcf="gendb://combinedDB" # Note with parallelizing, this is a placeholder
 	    elif checkVersion gatk 3.8.0 ; then
             gatkVer=3
             input_gvcf="${GVCF_LIST}"
@@ -438,8 +476,20 @@ case "${ROUTINE}" in
 	    fi
         GG_MEM=$(getMemory "${GG_QSUB}") # Figure out memory requirements based on the Qsub settings
         SINGLE_ARRAY_LIMIT=$[${NUM_CHR} - 1] # Get the maximum number of Torque tasks (# in array - 1)
-        if [[ ! -z "${CUSTOM_INTERVALS}" ]]; then SINGLE_ARRAY_LIMIT="${NUM_CHR}"; fi # If we have scaffolds, add one to the maximum array index
-	    if [ "${SINGLE_ARRAY_LIMIT}" -lt 0 ]; then echo "Please set NUM_CHR > 0. Or if NUM_CHR=0, set CUSTOM_INTERVALS" >&2; exit 1; fi
+        if [[ ! -z "${CUSTOM_INTERVALS}" ]]; then
+            if [[ "${PARALLELIZE}" == "true" ]]; then
+                # Use CUSTOM_INTERVALS to determine array limit
+                NUM_INTVLS=$(wc -l "${CUSTOM_INTERVALS}" | cut -d ' ' -f 1)
+                SINGLE_ARRAY_LIMIT=$[${NUM_INTVLS} - 1]
+            else
+                # If we have scaffolds, add one to the maximum array index
+                SINGLE_ARRAY_LIMIT="${NUM_CHR}"
+            fi
+        fi
+	    if [ "${SINGLE_ARRAY_LIMIT}" -lt 0 ]; then
+            echo "Please set NUM_CHR > 0. Or if NUM_CHR=0, set CUSTOM_INTERVALS" >&2
+            exit 1
+        fi
         echo "Max array index is ${SINGLE_ARRAY_LIMIT}...">&2
 	    if [[ "$USE_PBS" == true ]]; then
             if [[ "${SINGLE_ARRAY_LIMIT}" -ne 0 ]]
@@ -448,14 +498,14 @@ case "${ROUTINE}" in
                 if [[ -z ${CUSTOM_JOB_ARR+x} ]]
                 then
                     echo "Using default array limit from 0 to ${SINGLE_ARRAY_LIMIT}"
-		            echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Genotype_GVCFs.sh && Genotype_GVCFs ${input_gvcf} ${OUT_DIR} ${GATK_JAR} ${REF_GEN} ${THETA} ${PLOIDY} ${GG_MEM} ${REF_DICT} ${SINGLE_ARRAY_LIMIT} ${gatkVer} ${CUSTOM_INTERVALS}" | qsub -t 0-"${SINGLE_ARRAY_LIMIT}" -q "${GG_QUEUE}" -l "${GG_QSUB}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}"_Genotype_GVCFs
+		            echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Genotype_GVCFs.sh && Genotype_GVCFs ${input_gvcf} ${OUT_DIR} ${GATK_JAR} ${REF_GEN} ${THETA} ${PLOIDY} ${GG_MEM} ${REF_DICT} ${SINGLE_ARRAY_LIMIT} ${gatkVer} ${CUSTOM_INTERVALS}" "${PARALLELIZE}" | qsub -t 0-"${SINGLE_ARRAY_LIMIT}" -q "${GG_QUEUE}" -l "${GG_QSUB}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}"_Genotype_GVCFs
                 else
                     # Use job arrays following -t flag
                     echo "Using custom job arrays following -t flag: ${CUSTOM_JOB_ARR}" >&2
-                    echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Genotype_GVCFs.sh && Genotype_GVCFs ${input_gvcf} ${OUT_DIR} ${GATK_JAR} ${REF_GEN} ${THETA} ${PLOIDY} ${GG_MEM} ${REF_DICT} ${SINGLE_ARRAY_LIMIT} ${gatkVer} ${CUSTOM_INTERVALS}" | qsub -t "${CUSTOM_JOB_ARR}" -q "${GG_QUEUE}" -l "${GG_QSUB}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}"_Genotype_GVCFs
+                    echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Genotype_GVCFs.sh && Genotype_GVCFs ${input_gvcf} ${OUT_DIR} ${GATK_JAR} ${REF_GEN} ${THETA} ${PLOIDY} ${GG_MEM} ${REF_DICT} ${SINGLE_ARRAY_LIMIT} ${gatkVer} ${CUSTOM_INTERVALS}" "${PARALLELIZE}" | qsub -t "${CUSTOM_JOB_ARR}" -q "${GG_QUEUE}" -l "${GG_QSUB}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}"_Genotype_GVCFs
                 fi
             else # If we have only one sample
-		        echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Genotype_GVCFs.sh && Genotype_GVCFs ${input_gvcf} ${OUT_DIR} ${GATK_JAR} ${REF_GEN} ${THETA} ${PLOIDY} ${GG_MEM} ${REF_DICT} ${SINGLE_ARRAY_LIMIT} ${gatkVer} ${CUSTOM_INTERVALS}" | qsub -t 0 -q "${GG_QUEUE}" -l "${GG_QSUB}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}"_Genotype_GVCFs
+		        echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Genotype_GVCFs.sh && Genotype_GVCFs ${input_gvcf} ${OUT_DIR} ${GATK_JAR} ${REF_GEN} ${THETA} ${PLOIDY} ${GG_MEM} ${REF_DICT} ${SINGLE_ARRAY_LIMIT} ${gatkVer} ${CUSTOM_INTERVALS}" "${PARALLELIZE}" | qsub -t 0 -q "${GG_QUEUE}" -l "${GG_QSUB}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}"_Genotype_GVCFs
 	        fi
 	    else # Without PBS
 	        source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Genotype_GVCFs.sh && Genotype_GVCFs "${input_gvcf}" "${OUT_DIR}" "${GATK_JAR}" "${REF_GEN}" ${THETA} ${PLOIDY} ${GG_MEM} "${REF_DICT}" ${SINGLE_ARRAY_LIMIT} ${gatkVer} ${CUSTOM_INTERVALS} >> "${ERROR}/Genotype_GVCFs.log" 2>&1
