adding Octopus variant calling handler

diff --git a/sequence_handling_fastp b/sequence_handling_fastp
--- a/sequence_handling_fastp
+++ b/sequence_handling_fastp
@@ -23,6 +23,7 @@ Where:  <handler> is one of:
                 13 | Clair3_Variant_Calling (long-read SNP/indel calling for ONT/PacBio)
                 14 | Bcftools_Mpileup_Variant_Calling (SNP-only lightweight alternative)
                 15 | GLnexus_Joint_Calling (joint variant calling for consolidating single-sample VCFs)
+                Octopus_Variant_Calling (short-read individual or population SNP/indel calling)
             Other handlers:
                 16 | Quality_Trimming
                 17 | Realigner_Target_Creator
@@ -1341,6 +1342,40 @@ case "${ROUTINE}" in
             sbatch --job-name=${PROJECT}_Bcftools_Mpileup ${VC_SBATCH} -o ${ERROR}/${PROJECT}_Bcftools_Mpileup.%j.out -e ${ERROR}/${PROJECT}_Bcftools_Mpileup.%j.err ${SEQUENCE_HANDLING}/SlurmJobScripts/Bcftools_Mpileup_Variant_Calling.job ${CONFIG} ${SEQUENCE_HANDLING}
         else
             (source "${CONFIG}" && source "${SEQUENCE_HANDLING}/Handlers/Bcftools_Mpileup_Variant_Calling.sh" && Bcftools_Mpileup_Variant_Calling "${FINISHED_BAM_LIST}" "${OUT_DIR}" "${REF_GEN}" "${THREADS}" "${TMP}") > "${ERROR}/Bcftools_Mpileup_Variant_Calling.log" 2>&1
+        fi
+        ;;
+    Octopus_Variant_Calling )
+        echo "$(basename $0): Running Octopus individual variant calling for short-read data..." >&2
+        if [[ "${SEQ_PLATFORM}" != "ILLUMINA" ]]; then
+            echo "Octopus_Variant_Calling is for short-read Illumina data. Current platform: ${SEQ_PLATFORM}" >&2
+            exit 1
+        fi
+        source "${SEQUENCE_HANDLING}/Handlers/Octopus_Variant_Calling.sh"
+        checkDependencies Octopus_Variant_Calling_Dependencies[@]
+        if [[ "$?" -ne 0 ]]; then
+            echo "Missing dependencies for Octopus_Variant_Calling, exiting..." >&2
+            exit 1
+        fi
+        checkSamples "${FINISHED_BAM_LIST}"
+        if [[ "$?" -ne 0 ]]; then exit 1; fi
+        checkBaiIndex "${FINISHED_BAM_LIST}"
+        if [[ "$?" -ne 0 ]]; then exit 1; fi
+        if [[ -z "${OCTOPUS_ERROR_MODEL:-}" ]]; then
+            echo "Please specify OCTOPUS_ERROR_MODEL in the config file." >&2
+            exit 1
+        fi
+
+        if [[ "$USE_PBS" == true ]] && [[ "$USE_SLURM" == true ]]; then
+            echo "USE_PBS and USE_SLURM are both set to true. Only one can be true, exiting..." >&2
+            exit 1
+        elif [[ "$USE_PBS" == true ]]; then
+            echo "PBS is our workload manager/job scheduler." >&2
+            echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Octopus_Variant_Calling.sh && Octopus_Variant_Calling ${FINISHED_BAM_LIST} ${OUT_DIR} ${REF_GEN} ${OCTOPUS_ERROR_MODEL} ${OCTOPUS_CALLING_MODEL} ${PLOIDY} ${OCTOPUS_THREADS}" | qsub -l "${OCTOPUS_QSUB}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}_Octopus_Variant_Calling"
+        elif [[ "${USE_SLURM}" == true ]]; then
+            echo "Slurm is our workload manager/job scheduler." >&2
+            sbatch --job-name="${PROJECT}_Octopus_Variant_Calling" ${OCTOPUS_SBATCH} -o "${ERROR}/${PROJECT}_Octopus_Variant_Calling.%j.out" -e "${ERROR}/${PROJECT}_Octopus_Variant_Calling.%j.err" "${SEQUENCE_HANDLING}/SlurmJobScripts/Octopus_Variant_Calling.job" "${CONFIG}" "${SEQUENCE_HANDLING}"
+        else
+            (source "${CONFIG}" && source "${SEQUENCE_HANDLING}/Handlers/Octopus_Variant_Calling.sh" && Octopus_Variant_Calling "${FINISHED_BAM_LIST}" "${OUT_DIR}" "${REF_GEN}" "${OCTOPUS_ERROR_MODEL}" "${OCTOPUS_CALLING_MODEL}" "${PLOIDY}" "${OCTOPUS_THREADS}") > "${ERROR}/Octopus_Variant_Calling.log" 2>&1
         fi
         ;;
     15 | GLnexus_Joint_Calling )
