Complete overhaul of Coverage_Mapping Functional for exome-capture Whole-genome still in progress

diff --git a/sequence_handling b/sequence_handling
--- a/sequence_handling
+++ b/sequence_handling
@@ -181,15 +181,17 @@ case "${ROUTINE}" in
         source "${SEQUENCE_HANDLING}"/Handlers/Coverage_Mapping.sh
         checkDependencies Coverage_Mapping_Dependencies[@] # Check to see if the dependencies are installed
         if [[ "$?" -ne 0 ]]; then exit 1; fi # If we're missing a dependency, exit out with error
-        checkVersion bedtools 2.23 # Check to see that we have bedtools version 2.23
-        if [[ "$?" -ne 0 ]]; then echo "Please use Bedtools version 2.23" >&2; exit 1; fi # If not, exit out with error
-        checkVersion R 3.3 # Check to see that we have R version 3.3.X
-        if [[ "$?" -ne 0 ]]; then echo "Please use R version 3.3.X" >&2; exit 1; fi # If not, exit out with error
+        checkVersion bedtools 2.17.0 # Check to see that we have bedtools version 2.17.0
+        if [[ "$?" -ne 0 ]]; then echo "Please use Bedtools version 2.17.0" >&2; exit 1; fi # If not, exit out with error
+        #checkVersion R 3.3 # Check to see that we have R version 3.3.X
+        #if [[ "$?" -ne 0 ]]; then echo "Please use R version 3.3.X" >&2; exit 1; fi # If not, exit out with error
         checkSamples "${BAM_LIST}" # Check to see if samples and sample list exists
         if [[ "$?" -ne 0 ]]; then exit 1; fi # If we're missing a sample or our list, exit out with error
-        if ! [[ -f "${REF_ANN}" ]]; then echo "Failed to find reference annotation file, exiting..." >&2; exit 1; fi # Check to see if the reference annotation file exists. If not, exit
-        #   Run Coverage_Mapping
-        echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Coverage_Mapping.sh && Coverage_Mapping ${BAM_LIST} ${OUT_DIR} ${REF_ANN} ${SEQUENCE_HANDLING}"  | qsub -l "${CM_QSUB}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}"_Coverage_Mapping
+        if ! [[ -f "${REGIONS_FILE}" ]]
+            then echo "No regions file found, assuming whole-genome sequencing data..." >&2
+            else echo "Using regions file at ${REGIONS_FILE} for exome capture data..." >&2
+        fi
+        echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Coverage_Mapping.sh && Coverage_Mapping ${BAM_LIST} ${OUT_DIR} ${REGIONS_FILE} ${PROJECT}" | qsub -l "${CM_QSUB}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}"_Coverage_Mapping
         ;;
     8|Indel_Realignment )
         echo "$(basename $0): Realigning reads near indels..." >&2
