moving changed files

diff --git a/sequence_handling_fastp b/sequence_handling_fastp
--- a/sequence_handling_fastp
+++ b/sequence_handling_fastp
@@ -49,6 +49,36 @@ Optional arguments:
 
 export -f Usage
 
+function resolve_minimap2_preset() {
+    local seq_platform="$1"
+    local read_type="${MINIMAP2_READ_TYPE:-}"
+    local preset=""
+
+    if [[ -n "${MINIMAP2_PRESET:-}" ]]; then
+        preset="${MINIMAP2_PRESET}"
+    elif [[ -n "${read_type}" ]]; then
+        case "${read_type}" in
+            PACBIO) preset="map-pb" ;;
+            PACBIO_HIFI|PACBIO-HiFi) preset="map-hifi" ;;
+            ONT) preset="map-ont" ;;
+            ONT_Q20|ONT-Q20) preset="lr:hq" ;;
+            *) echo "ERROR: Unknown MINIMAP2_READ_TYPE: ${read_type}" >&2; return 1 ;;
+        esac
+    else
+        if [[ "${seq_platform}" == "ONT" ]]; then preset="map-ont"; fi
+        if [[ "${seq_platform}" == "PACBIO" ]]; then preset="map-pb"; fi
+    fi
+
+    case ",map-ont,map-pb,map-hifi,lr:hq," in
+        *,${preset},*) ;;
+        *) echo "ERROR: Unsupported minimap2 preset: ${preset}. Valid: map-ont, map-pb, map-hifi, lr:hq" >&2; return 1 ;;
+    esac
+
+    printf '%s\n' "${preset}"
+}
+
+export -f resolve_minimap2_preset
+
 #   Where is 'sequence_handling' located?
 #   Mod by Naoki
 SCRIPT=$(realpath $0)  # Track back the symlink to find the actual location
@@ -159,35 +189,13 @@ case "${ROUTINE}" in
                 echo "Missing dependencies for Long_Read_Mapping, exiting..." >&2
                 exit 1
             fi
-            # Resolve minimap2 preset from config
-            PRESET=""
-            if [[ -n "${MINIMAP2_PRESET}" ]]; then
-                PRESET="${MINIMAP2_PRESET}"
-            elif [[ -n "${MINIMAP2_READ_TYPE}" ]]; then
-                case "${MINIMAP2_READ_TYPE}" in
-                    PACBIO) PRESET="map-pb" ;;
-                    PACBIO_HIFI|PACBIO-HiFi) PRESET="map-hifi" ;;
-                    ONT) PRESET="map-ont" ;;
-                    ONT_Q20|ONT-Q20) PRESET="lr:hq" ;;
-                    *) echo "ERROR: Unknown MINIMAP2_READ_TYPE: ${MINIMAP2_READ_TYPE}" >&2; exit 1 ;;
-                esac
-            else
-                # Fallback by platform
-                if [[ "${SEQ_PLATFORM}" == "ONT" ]]; then PRESET="map-ont"; fi
-                if [[ "${SEQ_PLATFORM}" == "PACBIO" ]]; then PRESET="map-pb"; fi
-            fi
-
-            # Validate preset against allowed list
-            case ",map-ont,map-pb,map-hifi,lr:hq," in
-                *,${PRESET},*) ;;
-                *) echo "ERROR: Unsupported minimap2 preset: ${PRESET}. Valid: map-ont, map-pb, map-hifi, lr:hq" >&2; exit 1 ;;
-            esac
+            PRESET="$(resolve_minimap2_preset "${SEQ_PLATFORM}")" || exit 1
 
             checkSamples "${TRIMMED_LIST}"
             if [[ "$?" -ne 0 ]]; then exit 1; fi
             
             # Get sample array for determining array job size
-            local -a sample_array
+            declare -a sample_array
             mapfile -t sample_array < <(grep -E ".fastq|.fastq.gz|.fasta|.fasta.gz|.fa|.fq|.fa.gz|.fq.gz" "${TRIMMED_LIST}")
             SINGLE_ARRAY_LIMIT=$[${#sample_array[@]} - 1]
             
@@ -305,6 +313,13 @@ case "${ROUTINE}" in
         fi  # End of BWA mem (short read) conditional
         ;;
     3 | SAM_Processing )
+        if [[ "${SEQ_PLATFORM}" == "ONT" || "${SEQ_PLATFORM}" == "PACBIO" ]]; then
+            echo "SAM_Processing is intended for SAM outputs from short-read mapping." >&2
+            echo "For SEQ_PLATFORM=${SEQ_PLATFORM}, Long_Read_Mapping already outputs sorted/indexed BAM files." >&2
+            echo "Skipping SAM_Processing to avoid redundant processing." >&2
+            exit 0
+        fi
+
         case "${METHOD}" in
             samtools )
                 echo "$(basename $0): Processing SAM files using SAMtools..." >&2
@@ -1513,19 +1528,45 @@ case "${ROUTINE}" in
         ;;
     3NP | NP_Read_Mapping )
         echo "$(basename $0): Mapping reads..." >&2
-        source "${SEQUENCE_HANDLING}/Handlers/NP_Read_Mapping.sh"
-        checkDependencies NP_Read_Mapping_Dependencies[@] # Check to see if the dependencies are installed
+        source "${SEQUENCE_HANDLING}/Handlers/Long_Read_Mapping.sh"
+        checkDependencies Long_Read_Mapping_Dependencies[@] # Check to see if dependencies are installed
         if [[ "$?" -ne 0 ]]; then exit 1; fi # If we're missing a dependency, exit out with error
+
+        if [[ -z "${SEQ_PLATFORM}" ]]; then
+            SEQ_PLATFORM="ONT"
+        fi
+        if [[ "${SEQ_PLATFORM}" != "ONT" && "${SEQ_PLATFORM}" != "PACBIO" ]]; then
+            echo "ERROR: 3NP/NP_Read_Mapping requires SEQ_PLATFORM=ONT (or PACBIO for compatible long-read runs)." >&2
+            exit 1
+        fi
+
+        PRESET="$(resolve_minimap2_preset "${SEQ_PLATFORM}")" || exit 1
+
         checkSamples "${RM_SAMPLE_LIST}" # Check to see if samples and sample list exists
         if [[ "$?" -ne 0 ]]; then exit 1; fi # If we're missing a sample or our list, exit out with error
-        declare -a RM_ARRAY=($(grep -E ".fastq|.fastq.gz|.fasta|.fasta.gz|.fa|.fq|.fa.gz|.fq.gz" "${RM_SAMPLE_LIST}")) # Create an array of the files
+        declare -a RM_ARRAY=($(grep -E ".fastq|.fastq.gz|.fasta|.fasta.gz|.fa|.fq|.fa.gz|.fq.gz" "${RM_SAMPLE_LIST}")) # Create an array of files
         SINGLE_ARRAY_LIMIT=$[${#RM_ARRAY[@]} - 1] # Get the maximum number of Torque tasks (# in array - 1)
         echo "Max array index is ${SINGLE_ARRAY_LIMIT}...">&2
-        if [[ "${SINGLE_ARRAY_LIMIT}" -ne 0 ]]
-        then # If we have enough samples for a task array
-            echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/NP_Read_Mapping.sh && NP_Read_Mapping ${RM_SAMPLE_LIST} ${OUT_DIR} ${OUTPUT_FORMAT} ${REF_GEN} ${REFERENCE_MINIMAP_INDEX} ${BANDWIDTH} ${MATCHING_SCORE} ${MISMATCH_PENALTY} ${GAP_OPEN_PENALTY} ${GAP_EXTENSION_PENALTY} ${Z_DROP_SCORE} ${MINIMAL_PEAK_DP_SCORE} ${THREADS}" | qsub -t 0-"${SINGLE_ARRAY_LIMIT}" -l "${RM_QSUB}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}"_NP_Read_Mapping
-        else # If we have only one sample
-            echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/NP_Read_Mapping.sh && NP_Read_Mapping ${RM_SAMPLE_LIST} ${OUT_DIR} ${OUTPUT_FORMAT} ${REF_GEN} ${REFERENCE_MINIMAP_INDEX} ${BANDWIDTH} ${MATCHING_SCORE} ${MISMATCH_PENALTY} ${GAP_OPEN_PENALTY} ${GAP_EXTENSION_PENALTY} ${Z_DROP_SCORE} ${MINIMAL_PEAK_DP_SCORE} ${THREADS}" | qsub -t 0 -l "${RM_QSUB}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}"_NP_Read_Mapping
+
+        if [[ "$USE_PBS" == true ]] && [[ "$USE_SLURM" == true ]]; then
+            echo "USE_PBS and USE_SLURM are both set to true. Only one can be true, exiting..." >&2
+            exit 1
+        elif [[ "$USE_PBS" == "true" ]]; then
+            if [[ -z ${CUSTOM_JOB_ARR+x} ]]; then
+                job_array_index_range="0-${SINGLE_ARRAY_LIMIT}"
+            else
+                job_array_index_range="${CUSTOM_JOB_ARR}"
+            fi
+            echo "source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Long_Read_Mapping.sh && Long_Read_Mapping ${RM_SAMPLE_LIST} ${PRESET} ${PROJECT} ${SEQ_PLATFORM} ${OUT_DIR} ${REF_GEN} ${THREADS}" | qsub -t "${job_array_index_range}" -l "${RM_QSUB}" -e "${ERROR}" -o "${ERROR}" -m abe -M "${EMAIL}" -N "${PROJECT}"_NP_Read_Mapping
+        elif [[ "${USE_SLURM}" == true ]]; then
+            if [[ -z ${CUSTOM_JOB_ARR+x} ]]; then
+                job_array_index_range="0-${SINGLE_ARRAY_LIMIT}"
+            else
+                job_array_index_range="${CUSTOM_JOB_ARR}"
+            fi
+            sbatch --job-name=${PROJECT}_NP_Read_Mapping --array=${job_array_index_range} ${RM_SBATCH} -o ${ERROR}/${PROJECT}_NP_Read_Mapping.%A_%a.out -e ${ERROR}/${PROJECT}_NP_Read_Mapping.%A_%a.err ${SEQUENCE_HANDLING}/SlurmJobScripts/Long_Read_Mapping.job ${CONFIG} ${SEQUENCE_HANDLING}
+        else
+            (source ${CONFIG} && source ${SEQUENCE_HANDLING}/Handlers/Long_Read_Mapping.sh && Long_Read_Mapping ${RM_SAMPLE_LIST} ${PRESET} ${PROJECT} ${SEQ_PLATFORM} ${OUT_DIR} ${REF_GEN} ${THREADS}) > ${ERROR}/NP_Read_Mapping.log 2>&1
         fi
         ;;
     4NP | NP_SAM_Processing )
